package com.leomaimoni.umh30editor

/**
 * UMH-30 protocol layer.
 *
 * IMPORTANT:
 * Only commands directly confirmed from the USB captures are placed here.
 * Routing read/write commands will be added after we validate their exact
 * SysEx bytes from the captured logs.
 */
object Umh30Protocol {

    private val header = byteArrayOf(
        0xF0.toByte(),
        0x00,
        0x21,
        0x5E
    )

    /**
     * Confirmed from the Wireshark capture:
     *
     * OUT payload:
     * F0 00 21 5E 02 02 00 F7
     *
     * This is the command generated by Set/save in MIDI Stream Config.
     */
    val saveCommand: ByteArray =
        header + byteArrayOf(0x02, 0x02, 0x00, 0xF7.toByte())

    fun toHex(bytes: ByteArray): String =
        bytes.joinToString(" ") { "%02X".format(it.toInt() and 0xFF) }
}
